before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -extldflags "-static"
      - -s -d -X version.Version={{ .Version }}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  name_template: "{{ .ProjectName }}-v{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
